# Default values for pulumi-operator-aws.
# This is a YAML-formatted file.
# Declare variables to be substituted into your templates.

# Global configuration
global:
  # Enable pre-delete hook to wait for stack resource deletion
  enablePreDeleteHook: true
  
  # Namespace configuration
  namespace:
    name: pulumi-aws
    labels:
      name: pulumi-aws
      purpose: demo-workloads
    create: false  # Let Helm handle namespace creation with --create-namespace

# AWS Configuration
aws:
  region: us-west-2
  # AWS credentials will be provided via secrets
  credentials:
    secretName: aws-credentials
    # These values will be base64 encoded by deployment scripts
    accessKeyId: ""
    secretAccessKey: ""

# Pulumi Configuration
pulumi:
  # Pulumi backend configuration
  backend:
    # Use local backend instead of Pulumi Cloud (recommended)
    useLocal: true
    # Passphrase for encrypting secrets in local backend
    passphrase: "local-backend-passphrase"
    
    # Persistence configuration for local backend
    persistence:
      # Enable persistent storage for backend state
      enabled: true
      # Storage class for the persistent volume
      # Use "" for default storage class, or specify a custom storage class
      storageClass: ""
      # Size of the persistent volume
      size: "10Gi"
      # Access modes for the persistent volume
      accessModes:
        - ReadWriteOnce
      # Additional annotations for the PVC
      annotations:
        # Add any storage-specific annotations here
        # Example for AWS EBS:
        # volume.beta.kubernetes.io/storage-class: "gp3"
        # volume.kubernetes.io/storage-provisioner: "ebs.csi.aws.com"
      # Optional: Selector to bind to a specific PV
      selector: {}
      # Optional: DataSource for volume cloning/restoration
      dataSource: {}
  
  # Pulumi access token secret (only needed when useLocal is false)
  accessToken:
    secretName: pulumi-access-token
    # This value will be base64 encoded by deployment scripts  
    token: ""
  
  # Pulumi image for workspace
  image: "pulumi/pulumi:latest-nonroot"
  
  # Pulumi project configuration
  project:
    name: aws-resources
    runtime: nodejs
    description: Deploy AWS resources using Pulumi Kubernetes Operator
  
  # Pulumi stack configuration
  stack:
    name: aws-resources
    environment: dev
    # Service account name for the workspace pod
    serviceAccountName: pulumi
    # Clean up AWS resources when the Stack is deleted
    destroyOnFinalize: true
    # Refresh the stack every 60 seconds to check for changes
    resyncFrequencySeconds: 60
    
    # Git repository configuration (optional - using ConfigMap instead)
    git:
      enabled: false
      repo: "https://github.com/pulumi/examples.git"
      repoDir: "aws-ts-s3-folder"
      branch: "master"
    
    # Use ConfigMap for Pulumi program instead of Git
    useConfigMap: true

# Project Configuration
project:
  name: pulumi-aws
  environment: dev
  bucketName: pulumi-aws-bucket
  tags:
    Environment: dev
    Project: pulumi-aws
    ManagedBy: pulumi-kubernetes-operator

# AWS Resources Configuration
# Control which AWS resources to provision
resources:
  # S3 Resources
  s3:
    # Create S3 bucket with versioning and encryption
    bucket:
      enabled: true
    # Block public access to the S3 bucket
    publicAccessBlock:
      enabled: true
  
  # VPC and Networking Resources
  vpc:
    # Create VPC with DNS support
    vpc:
      enabled: false
    # Create Internet Gateway for the VPC
    internetGateway:
      enabled: false  # Disabled since VPC is disabled
    # Create public subnet in the VPC
    publicSubnet:
      enabled: false  # Disabled since VPC is disabled
    # Create route table for public subnet
    routeTable:
      enabled: false  # Disabled since VPC is disabled
    # Associate route table with public subnet
    routeTableAssociation:
      enabled: false  # Disabled since VPC is disabled
  
  # Security Resources
  security:
    # Create security group for web servers (HTTP/HTTPS/SSH access)
    webSecurityGroup:
      enabled: false  # Disabled since VPC is disabled
  
  # IAM Resources
  iam:
    # Create IAM role for EC2 instances
    ec2Role:
      enabled: false
    # Create IAM policy for S3 access
    s3Policy:
      enabled: false
    # Attach S3 policy to EC2 role
    rolePolicyAttachment:
      enabled: false
    # Create instance profile for EC2 role
    instanceProfile:
      enabled: false

# Service Account Configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  name: pulumi
  # Additional annotations to add to the service account
  annotations: {}

# RBAC Configuration
rbac:
  # Specifies whether RBAC resources should be created
  create: true
  
  clusterRole:
    name: pulumi-stack-manager
    # Additional rules can be added here
    additionalRules: []

# Operator namespace (where the operator itself runs)
operatorNamespace: pulumi-kubernetes-operator

# ConfigMap configuration for the Pulumi program
configMap:
  name: pulumi-program
  
# Dependencies versions
dependencies:
  pulumi: "^3.88.0"
  pulumiAws: "^6.5.0"
  nodeTypes: "^20.0.0"
  typescript: "^5.0.0"

# Node.js configuration
nodejs:
  version: ">=18.0.0"

# TypeScript configuration
typescript:
  target: "ES2020"
  module: "commonjs"
  lib: ["ES2020"]
  strict: true
  esModuleInterop: true
  skipLibCheck: true
  forceConsistentCasingInFileNames: true
  moduleResolution: "node"
