# Example values file for Pulumi Operator AWS Helm Chart
# Copy this file and customize it for your deployment

# Global configuration
global:
  # Enable pre-delete hook to wait for stack resource deletion
  enablePreDeleteHook: true
  
  # Namespace configuration
  namespace:
    name: my-pulumi-aws-demo
    labels:
      name: my-pulumi-aws-demo
      purpose: demo-workloads
      team: platform
    create: true

# AWS Configuration
aws:
  region: us-east-1  # Change to your preferred region
  # AWS credentials will be provided via environment variables
  # and automatically base64 encoded by the deployment script
  credentials:
    secretName: aws-credentials
    # Leave these empty - they will be populated by the deployment script
    accessKeyId: ""
    secretAccessKey: ""

# Pulumi Configuration
pulumi:
  # Pulumi backend configuration
  backend:
    # Use local backend instead of Pulumi Cloud (recommended for self-managed)
    useLocal: true
    # Passphrase for encrypting secrets in local backend
    passphrase: "production-backend-passphrase-change-me"
    
    # Persistence configuration for local backend
    persistence:
      # Enable persistent storage for backend state (CRITICAL for production)
      enabled: true
      # Storage class for the persistent volume - customize based on your cluster
      # Examples: "gp3", "fast-ssd", "ssd", "premium-rwo"
      storageClass: "gp3"  # Use fast SSD storage for better performance
      # Size of the persistent volume - adjust based on your needs
      size: "20Gi"  # Larger size for production workloads
      # Access modes for the persistent volume
      accessModes:
        - ReadWriteOnce  # Standard for block storage
      # Additional annotations for the PVC
      annotations:
        # AWS EBS specific annotations (uncomment if using AWS EBS)
        volume.beta.kubernetes.io/storage-class: "gp3"
        # Enable encryption at rest
        # volume.beta.kubernetes.io/storage-encrypted: "true"
        # Backup/snapshot annotations
        backup.kubernetes.io/policy: "daily"
        # Cost tracking
        cost-center: "platform"
        team: "platform-team"
      # Optional: Selector to bind to a specific PV
      selector: {}
      # Optional: DataSource for volume cloning/restoration
      dataSource: {}
  
  # Pulumi access token secret (only needed when useLocal is false)
  accessToken:
    secretName: pulumi-access-token
    # Leave this empty - it will be populated by the deployment script
    token: ""
  
  # Pulumi project configuration
  project:
    name: aws-resources
    runtime: nodejs
    description: Deploy AWS resources using Pulumi Kubernetes Operator
  
  # Pulumi stack configuration
  stack:
    name: aws-resources
    environment: production  # Change to match your environment
    serviceAccountName: pulumi
    destroyOnFinalize: true
    resyncFrequencySeconds: 300  # 5 minutes instead of 60 seconds
    
    # Git repository configuration (disabled in favor of ConfigMap)
    git:
      enabled: false
      repo: "https://github.com/pulumi/examples.git"
      repoDir: "aws-ts-s3-folder"
      branch: "master"
    
    # Use ConfigMap for Pulumi program instead of Git
    useConfigMap: true

# Project Configuration
project:
  name: my-production-app
  environment: production
  bucketName: my-production-app-prod-bucket-12345  # Make sure this is globally unique
  tags:
    Environment: production
    Project: my-production-app
    ManagedBy: pulumi-kubernetes-operator
    Team: platform
    CostCenter: "CC-12345"
    Owner: "platform-team@company.com"

# AWS Resources Configuration
# Control which AWS resources to provision - customize based on your needs
resources:
  # S3 Resources
  s3:
    # Create S3 bucket with versioning and encryption
    bucket:
      enabled: true
    # Block public access to the S3 bucket  
    publicAccessBlock:
      enabled: true
  
  # VPC and Networking Resources
  vpc:
    # Create VPC with DNS support
    vpc:
      enabled: false  # Disable if you have an existing VPC
    # Create Internet Gateway for the VPC
    internetGateway:
      enabled: false  # Only needed if creating a new VPC
    # Create public subnet in the VPC
    publicSubnet:
      enabled: false  # Only needed if creating a new VPC
    # Create route table for public subnet
    routeTable:
      enabled: false  # Only needed if creating a new VPC
    # Associate route table with public subnet
    routeTableAssociation:
      enabled: false  # Only needed if creating a new VPC
  
  # Security Resources
  security:
    # Create security group for web servers (HTTP/HTTPS/SSH access)
    webSecurityGroup:
      enabled: false  # Disable if you have existing security groups
  
  # IAM Resources
  iam:
    # Create IAM role for EC2 instances
    ec2Role:
      enabled: true   # Usually needed for EC2 instances
    # Create IAM policy for S3 access
    s3Policy:
      enabled: true   # Usually needed if using S3
    # Attach S3 policy to EC2 role
    rolePolicyAttachment:
      enabled: true   # Usually needed if using IAM resources
    # Create instance profile for EC2 role
    instanceProfile:
      enabled: true   # Usually needed for EC2 instances

# Service Account Configuration
serviceAccount:
  create: true
  name: pulumi
  annotations:
    # Add any annotations you need
    # eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/pulumi-role

# RBAC Configuration
rbac:
  create: true
  clusterRole:
    name: pulumi-stack-manager
    # Add additional rules if needed
    additionalRules: []

# Operator namespace (where the operator itself runs)
operatorNamespace: pulumi-system  # Change if your operator is in a different namespace

# ConfigMap configuration for the Pulumi program
configMap:
  name: pulumi-program
  
# Dependencies versions - update as needed
dependencies:
  pulumi: "^3.100.0"
  pulumiAws: "^6.15.0"
  nodeTypes: "^20.10.0"
  typescript: "^5.3.0"

# Node.js configuration
nodejs:
  version: ">=18.0.0"

# TypeScript configuration
typescript:
  target: "ES2020"
  module: "commonjs"
  lib: ["ES2020"]
  strict: true
  esModuleInterop: true
  skipLibCheck: true
  forceConsistentCasingInFileNames: true
  moduleResolution: "node"
