apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: pulumi-kubernetes-operator
type: Opaque
data:
  # Base64 encoded AWS credentials
  # These will be populated by the deployment script
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_REGION: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: pulumi-access-token
  namespace: pulumi-kubernetes-operator
type: Opaque
data:
  # Base64 encoded Pulumi access token
  # This will be populated by the deployment script
  accessToken: ""
